language: cpp

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "ek8XdXiYRdTZZpVXpoDqKg"

common_sources: &all_sources
  - ubuntu-toolchain-r-test

addons:
  coverity_scan:
    build_command: make test
    branch_pattern: coverity_scan
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: COMPILER='g++-7'

    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: *all_sources
          packages: ['g++-9']
      env: COMPILER='g++-9'

before_script:
  - export CXX=${COMPILER}

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make test ; fi
