language: cpp
cache: ccache
dist: "trusty"

common_sources: &all_sources
  - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: *all_sources
          packages: ['g++-9', 'lcov']
      env: COMPILER='g++-9'

addons:
  apt:
    packages:
      - lcov
      - "python3"
      - "python3-pip"

before_install:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 90
  - pyenv global 3.6
  - pip3.6 install --upgrade pip
  - pip3.6 install --upgrade setuptools

install:
  - wget https://raw.githubusercontent.com/RPGillespie6/fastcov/master/fastcov.py

before_script:
  - export CXX=${COMPILER}
  - export fastcoverage="python3.6 fastcov.py"

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
