language: cpp

common_sources: &all_sources
  - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: *all_sources
          packages: ['g++-7']
      env: COMPILER='g++-7'

    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: *all_sources
          packages: ['g++-9']
      env: COMPILER='g++-9'

    - os: linux
      compiler: gcc
      addons: *gcc7
      env: COMPILER='g++-7'

    - os: linux
      compiler: gcc
      addons: *gcc9
      env: COMPILER='g++-9'

before_script:
  - export CXX=${COMPILER}

script: make test
