language: cpp
cache: ccache
dist: "trusty"

common_sources: &all_sources
  - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: *all_sources
          packages: ['g++-9', 'lcov']
      env: COMPILER='g++-9'

addons:
  apt:
    packages:
      - lcov
      - "python3"
      - "python3-pip"

before_install:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 90

install:
  - pyenv global 3.6
  - pip3.6 install --upgrade pip
  - pip3.6 install --upgrade setuptools
  - pip3.6 install git+https://github.com/rpgillespie6/fastcov.git

before_script:
  - export CXX=${COMPILER}
  # CODECOV_TOKEN
  - export secret:NXbR0Z5pqv1gvOM6gL4VpgAHG6QFdvB9quZzOELtKC83MJYRWm0L8sCl8SVRadOLiVBxrgdqHoMbdodrFnLFWryPkd6s4w1kVRpZtB81HbAF0ScjZx97jsfMzjU5fKlt

script:
  - fastcov --zerocounters
  - make coverage
  - fastcov --exclude /usr/include utils_lib/external --lcov -o $(OUTPUT_GCOV)/report.info

after_success: 
  - bash <(curl -s https://codecov.io/bash)
