comment: false
coverage:
    status:
        patch:
            default:
                target: '100'
        project:
            default:
                target: '100'
codecov:
  token: b5876245-49a1-4d59-8544-989a76f50289
