comment: false
coverage:
    status:
        patch:
            default:
                target: '90'
        project:
            default:
                target: '95'

ignore:
  - "utils_lib/external/"
  - "/usr/include"
